changed State into adState in AdapterStatus.gd and InitializationStat…
poingstudios/godot-admob-plugin pull request #149
Opened 2024-09-06 19:37 UTC by xzls-protik

…us.gd to avoid class_name conflict with State declaration

Failed parse script res://addons/admob/src/api/InitializationStatus.gd
  Invalid argument for "new()" function: argument 2 should be "State" but is "AdapterStatus.State".
  res://addons/admob/src/api/InitializationStatus.gd:37 - Parse Error: Invalid argument for "new()" function: argument 2 should be "State" but is "AdapterStatus.State".
  
  this error was being thrown if there was a class_name State anywhere in the project , added a fix for that .

2024-09-06 23:22 UTC, gumaciel requested changes

2024-09-06 23:22 UTC, gumaciel commented on addons/admob/src/api/core/AdapterStatus.gd
> +enum adState{
Please change to `InitializationState`

2024-09-07 04:26 UTC, xzls-protik commented
Done

2025-04-01 21:30 UTC, gumaciel approved these changes

2025-04-01 21:30 UTC, merged

2025-04-01 21:30 UTC, gumaciel commented
Thank you so much!